FROM node:10.17.0-alpine3.10

# RUN mkdir -p /srv/app/client
# WORKDIR /srv/app/client

# COPY package.json /srv/app/client
# COPY package-lock.json /srv/app/client

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# COPY . /srv/app/client
COPY . /usr/src/app

CMD ["npm", "start"]
